#lang info
(define collection "Summer2019")
(define deps '("base"))
(define build-deps '("scribble-lib" "racket-doc" "rackunit-lib"))
(define scribblings '(("scribblings/Summer2019.scrbl" ())
                      ("scribblings/tips-and-tricks.scrbl" ())  
                      ("scribblings/tactics-variants/tactics-variants.scrbl" ())))
(define pkg-desc "Description Here")
(define version "0.0")
(define pkg-authors '(thoughtstem))
