#!/usr/bin/racket

#lang racket

(require raco/command-name
         net/sendurl)

(define ts-kata-collection-name
 (last (explode-path (current-directory))))

(displayln (~a "Building " ts-kata-collection-name))

(delete-directory/files	(build-path (current-directory) "doc") #:must-exist? #f)

(displayln (~a "Rebuilding the docs with 'raco setup " ts-kata-collection-name "'"))

(and (system (~a "raco setup Summer2019/Kata-Collections/" ts-kata-collection-name))

     (send-url (~a "file://"
                   (build-path (current-directory) "doc/manual/index.html"))))

(displayln "Done")

